# Generated by Django 5.2.7 on 2026-02-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
