# Generated by Django 5.2.7 on 2026-02-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='lead_representative_photo',
            field=models.ImageField(blank=True, null=True, upload_to='application_photos/lead_representative/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='application',
            name='professional_photo',
            field=models.ImageField(blank=True, null=True, upload_to='application_photos/professional/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='application',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='application_photos/profile/%Y/%m/%d/'),
        ),
    ]
