# Generated by Django 6.0.1 on 2026-02-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_lead_representative_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='license_type',
            field=models.CharField(choices=[('profile', 'Profile License'), ('professional', 'Professional License'), ('lead_representative', 'Lead Representative License')], max_length=50),
        ),
    ]
