# Generated by Django 6.0.1 on 2026-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_license_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='lead_representative_photo',
        ),
        migrations.AddField(
            model_name='application',
            name='company_representative_photo',
            field=models.ImageField(blank=True, null=True, upload_to='application_photos/company_representative/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='license_type',
            field=models.CharField(choices=[('profile', 'Profile License'), ('professional', 'Professional License'), ('company_representative', 'Company Representative License')], max_length=50),
        ),
    ]
