# Generated by Django 6.0.1 on 2026-02-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='license_type',
            field=models.CharField(choices=[('profile', 'Profile License'), ('professional', 'Professional License'), ('company_representative', 'Company Representative License')], max_length=50),
        ),
    ]
