# Generated by Django 6.0.2 on 2026-02-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_application_license_type_applicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company_representative_photo',
            field=models.ImageField(blank=True, null=True, upload_to='application_photos/company_representative_photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='license_type',
            field=models.CharField(choices=[('Contractor License', 'Contractor License'), ('Professional License', 'Professional License'), ('Import/Export License', 'Import/Export License')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='professional_photo',
            field=models.ImageField(blank=True, null=True, upload_to='application_photos/professional_photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='application_photos/profile_photo/%Y/%m/%d/'),
        ),
    ]
