# Generated by Django 6.0.2 on 2026-02-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_company_representative_photo_and_more'),
        ('licenses', '0009_license_previous_license_alter_license_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_applications', to='licenses.license'),
        ),
    ]
