# Generated by Django 6.0.2 on 2026-02-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file'),
        ('vehicles', '0003_vehicle_chassis_number_vehicle_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle'),
        ),
    ]
