# Generated by Django 6.0.2 on 2026-02-15 06:45

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_upload_path, verbose_name='File Link'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Document Type'),
        ),
    ]
