# Generated by Django 6.0.2 on 2026-02-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Construction License Management System', max_length=255)),
                ('support_email', models.EmailField(default='support@clms.gov', max_length=254)),
                ('support_phone', models.CharField(default='+1-800-123-4567', max_length=64)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('auto_approval', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=30)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('password_min_length', models.IntegerField(default=8)),
                ('smtp_host', models.CharField(default='smtp.example.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(default='noreply@clms.gov', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('notification_template', models.TextField(default='Dear {name},\n\nYour application {id} has been {status}.\n\nThank you for using CLMS.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
