# Generated by Django 6.0.2 on 2026-02-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=20),
        ),
    ]
