# Generated by Django 6.0.2 on 2026-02-12 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0003_partnership_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='partners',
        ),
        migrations.AddField(
            model_name='partnership',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='ownership_ratio_main',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=5),
        ),
        migrations.AddField(
            model_name='partnership',
            name='ownership_ratio_partner',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AddField(
            model_name='partnership',
            name='partnership_type',
            field=models.CharField(choices=[('joint_venture', 'Joint Venture'), ('subcontract', 'Subcontract'), ('foreign_local', 'Foreign-Local'), ('consortium', 'Consortium')], default='joint_venture', max_length=32),
        ),
        migrations.AddField(
            model_name='partnership',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr/partnerships/'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_partner_approval', 'Awaiting Partner Approval'), ('awaiting_government_review', 'Awaiting Government Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=64, null=True)),
                ('license_number', models.CharField(blank=True, max_length=64, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partnership',
            name='main_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_partnerships', to='partnerships.company'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='partner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partnerships', to='partnerships.company'),
        ),
        migrations.CreateModel(
            name='PartnershipApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('actor_role', models.CharField(blank=True, max_length=32, null=True)),
                ('actor_identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='partnerships.partnership')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='partnerships/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partnerships.partnership')),
            ],
        ),
    ]
