# Generated by Django 6.0.2 on 2026-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0005_add_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='cp_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
