# Generated by Django 4.2.7 on 2026-02-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0006_partnership_cp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='cp_id',
        ),
    ]
