# Generated by Django 6.0.1 on 2026-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_alter_license_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('profile', 'Contractor License'), ('professional', 'Professional License'), ('company_representative', 'Import/Export License')], max_length=50),
        ),
    ]
