# Generated by Django 6.0.2 on 2026-02-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_alter_license_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('Contractor License', 'Contractor License'), ('Professional License', 'Professional License'), ('Import/Export License', 'Import/Export License')], max_length=50),
        ),
    ]
