# Generated by Django 6.0.2 on 2026-02-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_alter_license_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='previous_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='licenses.license'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='pending', max_length=20),
        ),
    ]
